version: 2

references:
  docker_default: &docker_8
    working_directory: /tmp/app
    docker:
      - image: node:8
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Taipei"

jobs:
  dependencies:
    <<: *docker_8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "yarn.lock"}}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            yarn config set cache-folder .yarn-cache
            yarn
      - save_cache:
          key:  v1-dependencies-{{checksum "yarn.lock"}}
          paths:
            - .yarn-cache
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  lint:
    <<: *docker_8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: lint js
          command: npm run lint:js -- --color
      - run:
          name: lint css
          command: npm run lint:css -- --color
  deploy:
    <<: *docker_8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Set git config
          command: |
            git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
            git config --global user.name "$GH_NAME" > /dev/null 2>&1
      - run: yarn run deploy

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - deploy:
          requires:
            - lint
          filters:
            branches:
              only:
                - source
